name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 712a47f946b98c30097eb1ada086ea00b18681ec

    - name: Build C Code
      run: |
       cd C
       make blurhash_encoder
       make blurhash_decoder
